name: Build and publish Docker image on push

on: push

env:
  DOCKER_CLI_EXPERIMENTAL: enabled

jobs:
  build:
    name: Build Docker image
    runs-on: self-hosted
    steps:
      - name: Set BRANCH
        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Checkout project
        uses: actions/checkout@v2.4.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.6.2

      - name: Setup Docker buildx action
        uses: docker/setup-buildx-action@v1.6.0

      - name: Run Docker buildx
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --tag ${{ secrets.DOCKER_HUB_USER }}/umbrel-monero:$BRANCH \
          --push .